include themes/codedark.conf
# include themes/one_dark.conf
# include themes/leaf-darkest.conf

window_padding_width 10
# font_family NotoSansMono Nerd Font Mono
# font_family Hack Nerd Font Mono
# font_family RobotoMono Nerd Font Mono
font_family UbuntuMono Nerd Font Mono
# font_family CodeNewRoman Nerd Font
# font_family Arimo Nerd Font Mono
# font_family JetBrainsMono Nerd Font Mono
# font_family Iosevka Term
# font_family FantasqueSansMono Nerd Font Mono
# font_family FiraCode Nerd Font Mono
# font_family Source Code Pro
font_size 17
# adjust_line_height 130%

# background_opacity 0.8
# background_opacity 0.9
# background #000000

# shell_integration no-cursor
cursor #fefefe
cursor_shape block
# cursor_blink_interval 0
