#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &

bspc monitor HDMI-0 -d 6 7 8 9 0
bspc monitor DP-1 -d 1 2 3 4 5

bspc config border_width        1
bspc config window_gap          6

bspc config normal_border_color \#fefefe
bspc config active_border_color \#fefefe
bspc config focused_border_color \#ffffff

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='2'
bspc rule -a discord desktop='3'
bspc rule -a Spotify desktop='0'
bspc rule -a Mail desktop='8'
bspc rule -a mpv manage=off state=floating

picom &
nitrogen --restore &
~/.config/polybar/launch.sh & 
 
flatpak run com.discordapp.Discord &
flatpak run com.spotify.Client &
flatpak run com.github.Eloston.UngoogledChromium &
thunderbird &

xrandr --output DP-1 --left-of HDMI-0
xrandr --output DP-1 --primary
xset -r rate 300 50
setxkbmap eu
